// Route paths. Values are the existing URLs — never change them here without
// updating the backend/mobile deep links (lib/myNotifications.ts).
export const ROUTES = {
  SIGN_IN: '/',
  SIGN_UP: '/auth/sign-up',
  DASHBOARD: '/dashboard',
  DAILY_ATTENDANCE: '/dashboard/attendance',
  SETTINGS_COMPANY: '/dashboard/settings/company',
  SETTINGS_NOTIFICATION: '/dashboard/settings/notification',
  SETTINGS_NOTIFICATION_ALERT: '/dashboard/settings/notification-alert',
  SETTINGS_THEME: '/dashboard/settings/theme',
  SUBJECTS: '/subjects',
  CLASSES: '/classes',
  FEES: '/fees',
  EXPENSES: '/expenses',
  ENQUIRIES: '/enquiries',
  TEACHERS: '/teachers',
  TEACHER_DAILY_ACTIVITIES: '/teachers/daily-activities',
  STAFF: '/staff',
  STUDENTS: '/students',
  STUDENT_ACTIVITIES: '/students/activities',
  STUDENT_ACTIVITY_TOPIC: '/students/activities/:activityId/topic',
  STUDENT_ASSESSMENTS: '/students/assessments',
  ASSESSMENTS: '/assessments',
  SEARCH: '/search',
  APPROVALS: '/approvals',
  APPROVALS_GENERATED_CONTENT: '/approvals/generated-content',
  PROFILE: '/profile',
  MY_ATTENDANCE: '/my-attendance',
  NOTICES: '/notices',
  MY_NOTIFICATIONS: '/my-notifications',
  NOTIFICATIONS: '/notifications',
  ATTENDANCE_CORRECTIONS: '/admin/attendance-corrections',
  FACTS: '/facts',
  ADMIN_FACTS: '/admin/facts',
  INSIGHTS: '/insights',
  ACADEMIC_YEARS: '/academic-years',
  TOPICS: '/topics',
  TOPIC_QUESTIONS: '/topics/:topicId/questions',
  CHAPTERS: '/chapters',
  CHAPTER_DETAIL: '/chapters/:chapterId',
  LIBRARY_CHAPTERS: '/library/chapters',
  LIBRARY_CHAPTER_DETAIL: '/library/chapters/:chapterId',
  LIBRARY_TOPICS: '/library/topics',
  LIBRARY_TOPIC_DETAIL: '/library/topics/:topicId',
} as const
