// Permission keys as issued by the backend (`user.permissions`). The string
// values are the contract — do not rename.
export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  DASHBOARD_STATS_STUDENTS: 'dashboard.stats.students',
  DASHBOARD_STATS_TEACHERS: 'dashboard.stats.teachers',
  DASHBOARD_STATS_ACTIVITIES: 'dashboard.stats.activities',
  DASHBOARD_STATS_EARNINGS: 'dashboard.stats.earnings',
  DASHBOARD_STATS_EXPENSES: 'dashboard.stats.expenses',
  DASHBOARD_PENDING_ACTIONS: 'dashboard.pending_actions',
  DASHBOARD_NOTIFY_PENDING_ACTIONS: 'dashboard.notify_pending_actions',
  DASHBOARD_ACTIVITY_GAPS: 'dashboard.activity_gaps',
  DASHBOARD_NOTIFY_ACTIVITY_GAPS: 'dashboard.notify_activity_gaps',
  DASHBOARD_BIRTHDAYS: 'dashboard.birthdays',
  DASHBOARD_GHOST_STUDENTS: 'dashboard.ghost_students',
  DASHBOARD_UNASSIGNED_STUDENTS: 'dashboard.unassigned_students',
  DASHBOARD_TOP_STUDENTS: 'dashboard.top_students',
  ACTIVITY_LOGS_VIEW: 'activity_logs.view',
  ATTENDANCE_VIEW: 'attendance.view',
  ATTENDANCE_MARK: 'attendance.mark',
  ATTENDANCE_CORRECTIONS: 'attendance.corrections',
  STUDENTS_VIEW: 'students.view',
  STUDENTS_MANAGE: 'students.manage',
  TEACHERS_VIEW: 'teachers.view',
  TEACHERS_MANAGE: 'teachers.manage',
  STAFF_MANAGE: 'staff.manage',
  SUBJECTS_MANAGE: 'subjects.manage',
  CLASSES_MANAGE: 'classes.manage',
  ACADEMIC_YEARS_MANAGE: 'academic_years.manage',
  FEES_VIEW: 'fees.view',
  FEES_MANAGE: 'fees.manage',
  EXPENSES_VIEW: 'expenses.view',
  EXPENSES_MANAGE: 'expenses.manage',
  ENQUIRIES_VIEW: 'enquiries.view',
  ENQUIRIES_MANAGE: 'enquiries.manage',
  ASSESSMENTS_VIEW: 'assessments.view',
  ASSESSMENTS_MANAGE: 'assessments.manage',
  ASSESSMENTS_GRADE: 'assessments.grade',
  DAILY_ACTIVITIES_APPROVE: 'daily_activities.approve',
  GENERATED_CONTENT_APPROVE: 'generated_content.approve',
  CONTENT_LIBRARY_MANAGE: 'content_library.manage',
  FACTS_MANAGE: 'facts.manage',
  INSIGHTS_VIEW: 'insights.view',
  NOTIFICATIONS_MANAGE: 'notifications.manage',
} as const

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
